import{a as S,S as _,i as a}from"./assets/vendor-DDdXnYQq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();const b="51915811-ff4e89c2eae9a908c3a29b564",v="https://pixabay.com/api/",A=15,R={key:b,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:A},g=async(r,t=1)=>{const n={...R};n.q=r,n.page=t;try{const s=await S.get(v,{params:n});return s.data.hits.length===0?"Sorry, there are no images matching your search query. Please try again!":s.data.hits}catch(s){throw console.error("Error fetching images:",s),s}},$=new _(".gallery a",{captionsData:"alt",captionDelay:250}),f=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector("#load-more");function u(){f.innerHTML=""}function h(r){const t=r.map(({largeImageURL:n,webformatURL:s,tags:e,likes:o,views:i,comments:P,downloads:w})=>`
        <a class="gallery__link" href="${n}">
          <img class="gallery__image" src="${s}" alt="${e}" loading="lazy" />
          <div class="info">
            <p>Likes: ${o}</p>
            <p>Views: ${i}</p>
            <p>Comments: ${P}</p>
            <p>Downloads: ${w}</p>
          </div>
        </a>
      `).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function q(){p.classList.remove("hidden")}function l(){p.classList.add("hidden")}const M=document.querySelector(".form");l();let c="",d=1;const E=15;M.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),d=1,!c){a.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}try{y(),l();const t=await g(c,d);if(typeof t=="string"){a.error({title:"Error",message:t,position:"topRight"}),u();return}u(),h(t),a.success({title:"Success",message:`Found ${t.length} images`,position:"topRight"}),t.length===E&&q()}catch(t){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{L()}});document.querySelector("#load-more").addEventListener("click",async()=>{d+=1;try{y();const r=await g(c,d);if(typeof r=="string"||r.length===0){l();return}h(r),r.length<E&&l()}catch(r){a.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(r)}finally{L()}});
//# sourceMappingURL=index.js.map
