import{a as S,S as v,i}from"./assets/vendor-DDdXnYQq.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const R="51915811-ff4e89c2eae9a908c3a29b564",b="https://pixabay.com/api/",_=15,$={key:R,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:_},u=async(o,e=1)=>{const n={...$};n.q=o,n.page=e;try{const s=await S.get(b,{params:n});return s.data.hits.length===0?"Sorry, there are no images matching your search query. Please try again!":s.data.hits}catch(s){throw console.error("Error fetching images:",s),s}},q=new v(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),h=document.querySelector(".loader"),f=document.querySelector("#load-more");function A(){g.innerHTML=""}function m(o){const e=o.map(({largeImageURL:n,webformatURL:s,tags:t,likes:r,views:a,comments:E,downloads:P})=>`
        <a class="gallery__link" href="${n}">
          <img class="gallery__image" src="${s}" alt="${t}" loading="lazy" />
          <div class="info">
            <p>Likes: ${r}</p>
            <p>Views: ${a}</p>
            <p>Comments: ${E}</p>
            <p>Downloads: ${P}</p>
          </div>
        </a>
      `).join("");g.insertAdjacentHTML("beforeend",e),q.refresh()}function p(){h.classList.remove("hidden")}function y(){h.classList.add("hidden")}function L(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const B=document.querySelector(".form"),M=document.querySelector("#load-more");d();let c="",l=1;const w=15;B.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),l=1,!c){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}try{p(),d(),A();const e=await u(c,l);if(typeof e=="string"){i.error({title:"Error",message:e,position:"topRight"});return}m(e),i.success({title:"Success",message:`Found ${e.length} images in this batch`,position:"topRight"}),e.length===w?L():i.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"})}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(e)}finally{y()}});M.addEventListener("click",async()=>{l+=1;try{p(),d();const o=await u(c,l);if(typeof o=="string"||o.length===0){i.info({title:"Info",message:"No more images available.",position:"topRight"});return}m(o);const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),o.length===w?L():i.info({title:"Info",message:"You've reached the end of search results.",position:"topRight"})}catch(o){i.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(o)}finally{y()}});
//# sourceMappingURL=index.js.map
